version: "3.9"
services:
  ack:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ack
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
    volumes:
      - ./config.yml:/app/config.yml
    ports:
      - 3000:3000
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: ack
    ports:
      - 27017:27017
    volumes:
      - database-data:/data/db
      - ./initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - app-network
      
networks:
  app-network:
      driver: bridge

volumes:
    database-data:
        driver: local